'use strict';


export const FETCH_SEED_DATA = 'FETCH_SEED_DATA';
export const LOAD_SEED_DATA = 'LOAD_SEED_DATA';
export const LOG_EVENT_MODAL_DATA = 'LOG_EVENT_MODAL_DATA';
export const TOGGLE_EVENT_MODAL = 'TOGGLE_EVENT_MODAL';
