'use strict';


export const FETCH_SEED_DATA_SUCCESS = 'FETCH_SEED_DATA_SUCCESS';
export const LOG_EVENT_MODAL_DATA = 'LOG_EVENT_MODAL_DATA';
export const TOGGLE_EVENT_MODAL = 'TOGGLE_EVENT_MODAL';
export const ADD_SINGLE_EVENT_SUCCESS = 'ADD_SINGLE_EVENT_SUCCESS';
export const DELETE_SINGLE_EVENT_SUCCESS = 'DELETE_SINGLE_EVENT_SUCCESS';
export const UPDATE_EVENT_DATA = 'UPDATE_EVENT_DATA';
export const ALLOW_BATCH_SELECTION = 'ALLOW_BATCH_SELECTION';
export const ADD_EVENT_TO_BATCH = 'ADD_EVENT_TO_BATCH';
export const DELETE_BATCH_EVENTS_SUCCESS = 'DELETE_BATCH_EVENTS_SUCCESS';
export const CLEAR_BATCH = 'CLEAR_BATCH';
export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS';
export const FETCH_STARRED_EVENTS_SUCCESS = 'FETCH_STARRED_EVENTS_SUCCESS';
export const FETCH_RECENTLY_MODIFIED_EVENTS_SUCCESS = 'FETCH_RECENTLY_MODIFIED_EVENTS_SUCCESS';
export const FETCH_CLOUDINARY_IMAGES = 'FETCH_CLOUDINARY_IMAGES';
