'use strict';


export const FETCH_SEED_DATA = 'FETCH_SEED_DATA';
export const LOAD_SEED_DATA = 'LOAD_SEED_DATA';
export const LOG_EVENT_MODAL_DATA = 'LOG_EVENT_MODAL_DATA';
export const TOGGLE_EVENT_MODAL = 'TOGGLE_EVENT_MODAL';
export const ADD_NEW_EVENT_DATA = 'ADD_NEW_EVENT_DATA';
export const DELETE_SINGLE_EVENT = 'DELETE_SINGLE_EVENT';
export const UPDATE_EVENT_DATA = 'UPDATE_EVENT_DATA';
export const ALLOW_BATCH_SELECTION = 'ALLOW_BATCH_SELECTION';
export const ADD_EVENT_TO_BATCH = 'ADD_EVENT_TO_BATCH';
export const DELETE_BATCH_EVENTS_SUCCESS = 'DELETE_BATCH_EVENTS_SUCCESS';
export const CLEAR_BATCH = 'CLEAR_BATCH';
